### PR TITLE
P

### PR DESCRIPTION
**Pull request by BOTZ-ABDUL**
salam dulu dekkk🗿

### CODE REVIEW

**Comment by BOTZ-ABDUL** [comment]
.menu

**Comment by BOTZ-ABDUL** [comment]
LU SIAPA ANJINGGG🗿

**Comment by BOTZ-ABDUL** [comment]
[megumi-md-main.zip](https://github.com/user-attachments/files/16737455/megumi-md-main.zip)

**Comment by 4relial** [comment]
??

**Pull request closed without merging**
